# Generated by Django 4.1 on 2022-08-11 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('balance', models.PositiveIntegerField(default=20000, verbose_name='موجودی کیف پول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مجموع پرداختی')),
                ('status', models.IntegerField(choices=[(1, 'در حال خرید'), (2, 'ثبت شده'), (3, 'لغو شده'), (4, 'ارسال شده')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='OrderRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='market.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لیست سفارش',
                'verbose_name_plural': 'لیست سفارش',
            },
        ),
    ]
